### ISSUE TITLE
Support for tailwindUI?

### ISSUE THREAD

**Issue by connecteev** [stursby/nuxt-tailwind-purgecss#4]
@stursby thanks for the repo! Has it been tested with and does it support tailwindUI? 
https://tailwindui.com/documentation#getting-set-up

TailwindUI requires changes to the postcss config:
https://tailwindui.com/documentation#update-your-purgecss-configuration

But changes to the postcss config are deprecated by nuxt: https://nuxtjs.org/faq/postcss-plugins/ 
So I'm confused as to how to make changes to a postcss config with nuxt.

**Comment by stursby** [comment]
@connecteev Haven't used TailwindUI, but got a quick demo working in the [tailwind-ui branch](https://github.com/stursby/nuxt-tailwind-purgecss/tree/tailwind-ui). You just have to modify the extractors for it to work.

And here's a demo URL --> https://5e9dc93a6d53d85578058260--nuxt-tailwind-purgecss.netlify.app/

And here's all the changes to get it working --> https://github.com/stursby/nuxt-tailwind-purgecss/compare/tailwind-ui

**Comment by connecteev** [comment]
@stursby works like a charm. Thanks for the quick response!
